- name: install epel-release
  yum: 
    name: epel-release
    state: present
    
- name: install apache server 
  yum: 
    name: httpd
    state: present

- name: "Desactivation et arret du serveur nginx"
  systemd:
    name: nginx
    state: stopped
    enabled: no
